apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: etos
build:
  artifacts:
    - image: ghcr.io/eiffel-community/etos-controller
      docker:
        dockerfile: Dockerfile
      hooks:
        after:
          - command:
            - make
            - build-installer
manifests:
  rawYaml:
  - dist/install.yaml
