apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/eiffel-community/etos-suite-runner//manifests/base?ref=5.3.4
  - github.com/eiffel-community/etos-suite-starter//manifests/base?ref=2.7.3
  - github.com/eiffel-community/etos-api//manifests/base?ref=2.9.3
components:
  - ../etcd
