apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/eiffel-community/etos-suite-runner//manifests/base?ref=4.1.1
  - github.com/eiffel-community/etos-environment-provider//manifests/base?ref=3.2.2
  - github.com/eiffel-community/etos-suite-starter//manifests/base?ref=2.4.0
  - github.com/eiffel-community/etos-api//manifests/base?ref=2.1.1
components:
  - ../etcd
